services:
  db:
    image: postgres:latest
    container_name: incrementum_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: Incr_DB
      POSTGRES_USER: Incr
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data

  api:
    build:
      context: ./Incrementum.api
    container_name: incrementum_api
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=development
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - KEYCLOAK_REALM_URL=https://auth-dev.snowse.io/realms/DevRealm
      - KEYCLOAK_CLIENT_ID=incrementum-client
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET:-}
    restart: unless-stopped
    depends_on:
      - db
  client:
    build:
      context: ./Incrementum.client
    container_name: incrementum_client
    ports:
      - "5173:5173"
    depends_on:
      - api
    restart: unless-stopped
    volumes:
      - ./Incrementum.client:/app
      - client_node_modules:/app/node_modules

volumes:
  client_node_modules:
  db_data:
