services:
  api:
    build:
      context: ./Incrementum.api
    container_name: incrementum_api
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=development
      - DB_CONN_STRING=${DB_CONN_STRING}
      - KEYCLOAK_REALM_URL=https://auth-dev.snowse.io/realms/incrementum
      - KEYCLOAK_CLIENT_ID=incrementum-client
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET:-}
      - POLYGON_API_KEY=${POLYGON_API_KEY}
    restart: unless-stopped
    volumes:
      - ./Incrementum.api:/Incrementum.api
  client:
    build:
      context: ./Incrementum.client
    container_name: incrementum_client
    ports:
      - "5173:5173"
    depends_on:
      - api
    restart: unless-stopped
    volumes:
      - ./Incrementum.client:/app
      - client_node_modules:/app/node_modules
    
  dash:
    build:
      context: ./Incrementum.api
    container_name: incrementum_dash
    command: sh -c "python InteractiveGraph.py"
    ports:
      - "8050:8050"
    volumes:
      - ./Incrementum.api:/Incrementum.api:ro

volumes:
  client_node_modules:
