apiVersion: v1
kind: Service
metadata:
  name: incrementum-api-service
  namespace: Incrementum
  labels:
    app: incrementum-api
spec:
  type: ClusterIP
  selector:
    app: incrementum-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
