apiVersion: v1
kind: Service
metadata:
  name: incrementum-client-service
  namespace: incrementum
  labels:
    app: incrementum-client
spec:
  type: ClusterIP
  selector:
    app: incrementum-client
  ports:
  - port: 80
    targetPort: 5173
    protocol: TCP
    name: http
